/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GiftIdRouteImport } from './routes/gift.$id'
import { Route as ApiPublicOgIdRouteImport } from './routes/api/public/og.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftIdRoute = GiftIdRouteImport.update({
  id: '/gift/$id',
  path: '/gift/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgIdRoute = ApiPublicOgIdRouteImport.update({
  id: '/api/public/og/$id',
  path: '/api/public/og/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gift/$id': typeof GiftIdRoute
  '/api/public/og/$id': typeof ApiPublicOgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gift/$id': typeof GiftIdRoute
  '/api/public/og/$id': typeof ApiPublicOgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gift/$id': typeof GiftIdRoute
  '/api/public/og/$id': typeof ApiPublicOgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gift/$id' | '/api/public/og/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gift/$id' | '/api/public/og/$id'
  id: '__root__' | '/' | '/gift/$id' | '/api/public/og/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GiftIdRoute: typeof GiftIdRoute
  ApiPublicOgIdRoute: typeof ApiPublicOgIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift/$id': {
      id: '/gift/$id'
      path: '/gift/$id'
      fullPath: '/gift/$id'
      preLoaderRoute: typeof GiftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/$id': {
      id: '/api/public/og/$id'
      path: '/api/public/og/$id'
      fullPath: '/api/public/og/$id'
      preLoaderRoute: typeof ApiPublicOgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GiftIdRoute: GiftIdRoute,
  ApiPublicOgIdRoute: ApiPublicOgIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
